steps:
# 1 Build docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west10-docker.pkg.dev/${PROJECT_ID}/nerja-rental-frontend-test/frontend-image', '.']
# 2 Push docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west10-docker.pkg.dev/${PROJECT_ID}/nerja-rental-frontend-test/frontend-image']

# terraform init
- id: 'terraform-init'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: 'sh'
  dir: infrastructure
  args: 
  - '-c'
  - |
    terraform init -backend-config test/backend.config

# terraform plan
- id: 'terraform-plan'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: 'sh'
  dir: infrastructure
  args: 
  - '-c'
  - |
    terraform plan -var-file test/settings.tfvars -out tfplan

# terraform apply
- id: 'terraform-apply'
  name: 'hashicorp/terraform:1.6.6'
  entrypoint: 'sh'
  dir: infrastructure
  args: 
  - '-c'
  - |
    terraform apply -auto-approve tfplan || exit 1
